//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowServiceTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointments_deleted
    {
        public string appointment_cd { get; set; }
        public Nullable<int> appointment_number { get; set; }
        public Nullable<System.Guid> customer_uid { get; set; }
        public string screening_cd { get; set; }
        public Nullable<System.DateTime> appt_time { get; set; }
        public Nullable<int> app_slot { get; set; }
        public string scantron { get; set; }
        public Nullable<int> no_show { get; set; }
        public Nullable<int> if_fill { get; set; }
        public Nullable<bool> inactive { get; set; }
        public Nullable<decimal> total_due { get; set; }
        public Nullable<decimal> paid { get; set; }
        public string appt_source { get; set; }
        public string price_sched_cd { get; set; }
        public string discount_cd { get; set; }
        public string appt_status_cd { get; set; }
        public Nullable<bool> walk_in { get; set; }
        public Nullable<decimal> AmendedTotalDue { get; set; }
        public Nullable<decimal> AmountDue { get; set; }
        public Nullable<decimal> original_bill_price { get; set; }
        public Nullable<decimal> original_paid { get; set; }
        public Nullable<decimal> Added_tests { get; set; }
        public Nullable<decimal> Deduct_tests { get; set; }
        public Nullable<decimal> reimbursements { get; set; }
        public Nullable<decimal> recon_adj { get; set; }
        public string original_discount { get; set; }
        public Nullable<System.Guid> appointment_cell_guid { get; set; }
        public Nullable<System.Guid> order_guid { get; set; }
        public Nullable<long> screening_id { get; set; }
        public string bloodcard_requisition_number { get; set; }
        public string scantron_form { get; set; }
        public string Team_Comments { get; set; }
        public Nullable<System.Guid> CStar_Participant_Guid { get; set; }
        public bool ImageDescrepancyAccountedFor { get; set; }
        public int ImageDescrepancyReasonId { get; set; }
        public int ImageDescrepancyTechId { get; set; }
        public Nullable<System.Guid> fsa_order_guid { get; set; }
        public int id { get; set; }
    }
}
