//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowServiceTemplate {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MsgResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MsgResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowServiceTemplate.MsgResource", typeof(MsgResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0001: Sending Facility(MSH.4) is required.{0}.
        /// </summary>
        internal static string M0001 {
            get {
                return ResourceManager.GetString("M0001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0002: Sending Facility should not exceed 10 characters:{0}{1}.
        /// </summary>
        internal static string M0002 {
            get {
                return ResourceManager.GetString("M0002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0003: Alt. Patient ID (PID.4) should not exceed 20 characters:{0}{1}.
        /// </summary>
        internal static string M0003 {
            get {
                return ResourceManager.GetString("M0003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0004: Patient Last Name(PID.5.1) should not exceed 25 characters:{0}{1}.
        /// </summary>
        internal static string M0004 {
            get {
                return ResourceManager.GetString("M0004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0005: Patient first name (PID.5.2) should not exceed 15 characters:{0}{1}.
        /// </summary>
        internal static string M0005 {
            get {
                return ResourceManager.GetString("M0005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0006: Patient Middle Initial (PID.5.3) should not exceed 15 characters:{0}{1}.
        /// </summary>
        internal static string M0006 {
            get {
                return ResourceManager.GetString("M0006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0007: Patient gender (PID.8.1) is invalid. Value should be &apos;M&apos; or &apos;1&apos; – Male/ &apos;F&apos; or &apos;0&apos; – Female / &apos;N&apos; – Not Indicated :{0}{1}.
        /// </summary>
        internal static string M0007 {
            get {
                return ResourceManager.GetString("M0007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0008: Patient Race (PID.10.1) is not valid. Race should be one of there letter: A|B|C|H|I|O|X|J|S:{0}{1}.
        /// </summary>
        internal static string M0008 {
            get {
                return ResourceManager.GetString("M0008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0009: Patient Address (PID.11.1) should not exceed 35 characters:{0}{1}.
        /// </summary>
        internal static string M0009 {
            get {
                return ResourceManager.GetString("M0009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0010: Patient City (PID.11.3) should not exceed 16 characters:{0}{1}.
        /// </summary>
        internal static string M0010 {
            get {
                return ResourceManager.GetString("M0010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0011: Patient race(PID.10) is required in LabCorp test order{0}.
        /// </summary>
        internal static string M0011 {
            get {
                return ResourceManager.GetString("M0011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0012: Patient &apos;s date of birth is required.{0}.
        /// </summary>
        internal static string M0012 {
            get {
                return ResourceManager.GetString("M0012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0013: ZIP code is not valid:{0}{1}LabCorp accepts a 5-position or 9-position ZIP code.  Do not send dashes.{2}.
        /// </summary>
        internal static string M0013 {
            get {
                return ResourceManager.GetString("M0013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0014: Patient phone number (PID.13) should be numeric characters(max is 10):{0}{1}.
        /// </summary>
        internal static string M0014 {
            get {
                return ResourceManager.GetString("M0014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0015: Account No should be 8 numeric characters. (but {0}){1}.
        /// </summary>
        internal static string M0015 {
            get {
                return ResourceManager.GetString("M0015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0016:Product {0}: Observation Battery Identifier is required{1}.
        /// </summary>
        internal static string M0016 {
            get {
                return ResourceManager.GetString("M0016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0017: Fasting flag value should be &apos;Y&apos; Or &apos;N&apos;{0}.
        /// </summary>
        internal static string M0017 {
            get {
                return ResourceManager.GetString("M0017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0018: Ordering Provider ID Number (ORC.12.1 or OBR.16.1) should not exceed 10 characters:{0}{1}.
        /// </summary>
        internal static string M0018 {
            get {
                return ResourceManager.GetString("M0018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0019: Ordering Provider Last Name (ORC.12.2) should not exceed 25 characters:{0}{1}.
        /// </summary>
        internal static string M0019 {
            get {
                return ResourceManager.GetString("M0019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0020: Ordering Provider First Initial (ORC.12.3) should not exceed 15 characters:{0}{1}.
        /// </summary>
        internal static string M0020 {
            get {
                return ResourceManager.GetString("M0020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0021: Number of test orders should not exceed 40 per patient:{0}{1}.
        /// </summary>
        internal static string M0021 {
            get {
                return ResourceManager.GetString("M0021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0022: Relevant Clinical Information should not exceed 64 characters:{0}.
        /// </summary>
        internal static string M0022 {
            get {
                return ResourceManager.GetString("M0022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0023: Please select at least one test order..
        /// </summary>
        internal static string M0023 {
            get {
                return ResourceManager.GetString("M0023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0024: Product {0}: LabCorp Order Code (OBR.4.1) should not exceed 15 characters:{1}{2}.
        /// </summary>
        internal static string M0024 {
            get {
                return ResourceManager.GetString("M0024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0025: Test Order Name (OBR.4.2) should not exceed 50 characters:{0}{1}.
        /// </summary>
        internal static string M0025 {
            get {
                return ResourceManager.GetString("M0025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0026:  No special characters are permitted. Patient&apos;s Last Name(PID.5.1) accept alpha characters only:{0}{1}.
        /// </summary>
        internal static string M0026 {
            get {
                return ResourceManager.GetString("M0026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0027:  No special characters are permitted, Patient&apos;s First Name(PID.5.2) accept alpha characters only:{0}{1}.
        /// </summary>
        internal static string M0027 {
            get {
                return ResourceManager.GetString("M0027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0028:  No special characters are permitted, Patient&apos;s Middle Name(PID.5.3) accept alpha characters only:{0}{1}.
        /// </summary>
        internal static string M0028 {
            get {
                return ResourceManager.GetString("M0028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0029: No special characters are permitted, Patient City (PID.11.3) accept alpha characters only:{0}{1}.
        /// </summary>
        internal static string M0029 {
            get {
                return ResourceManager.GetString("M0029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0030: Patient State (PID.11.4) is not upper case state abbreviation: {0} {1}.
        /// </summary>
        internal static string M0030 {
            get {
                return ResourceManager.GetString("M0030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0031:Product {0}:Observation Battery Tex is required.{1}.
        /// </summary>
        internal static string M0031 {
            get {
                return ResourceManager.GetString("M0031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0032: Life Line patient ID cannot exceed 20 characters{0}.
        /// </summary>
        internal static string M0032 {
            get {
                return ResourceManager.GetString("M0032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0033: Patient&apos;s Last Name(PID.5.1) is required..
        /// </summary>
        internal static string M0033 {
            get {
                return ResourceManager.GetString("M0033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0034: Patient &apos;s first name is required..
        /// </summary>
        internal static string M0034 {
            get {
                return ResourceManager.GetString("M0034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0035: Patient Gender (PID.18) is required.
        /// </summary>
        internal static string M0035 {
            get {
                return ResourceManager.GetString("M0035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0036: Ordering Provider First Initial (ORC.12.3) is required when Ordering Provider Last Name (ORC.12.2) is sent.{0}.
        /// </summary>
        internal static string M0036 {
            get {
                return ResourceManager.GetString("M0036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0037: Physician/Provider identifier(ORC.12.2) is required.{0}.
        /// </summary>
        internal static string M0037 {
            get {
                return ResourceManager.GetString("M0037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0038: NPI(ORC.12.1 or OBR.16.1) is required for all orders to identify the provider authorizing the test and/or authorizing the billing to a Third Party.{0}.
        /// </summary>
        internal static string M0038 {
            get {
                return ResourceManager.GetString("M0038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0039: Unique Foreign Accession / Specimen ID (ORC.2.1) is required.{0}.
        /// </summary>
        internal static string M0039 {
            get {
                return ResourceManager.GetString("M0039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0040: Unique Foreign Accession / Specimen ID (ORC.2.1) should not exceed 30 characters:{0}{1}.
        /// </summary>
        internal static string M0040 {
            get {
                return ResourceManager.GetString("M0040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0041: No special characters are permitted. Ordering Provider Last Name (ORC 12.2 or OBR.16.2) accept alpha characters only:{0}{1}.
        /// </summary>
        internal static string M0041 {
            get {
                return ResourceManager.GetString("M0041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0042: No special characters are permitted. Ordering Provider First Initial (ORC.12.2 or OBR.16.3) accepts alpha characters only:{0}{1}.
        /// </summary>
        internal static string M0042 {
            get {
                return ResourceManager.GetString("M0042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M0043: No test order selected.{0}.
        /// </summary>
        internal static string M0043 {
            get {
                return ResourceManager.GetString("M0043", resourceCulture);
            }
        }
    }
}
