//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsharpTemplate
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebData
    {
        public int Id { get; set; }
        public string TeamCode { get; set; }
        public System.DateTime ScreeningDate { get; set; }
        public int DataTypeId { get; set; }
        public string Data { get; set; }
        public string Status { get; set; }
    }
}
